# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\term5\tabibPy\GUI-using-PyQT5-python-master\GUI-using-PyQT5-python-master\Login Page with Database\tap.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PIL import Image, ImageEnhance, ImageFilter
import pytesseract
import sqlite3

class Ui_MainWindow(object):
    def __init__(self,phone):
        self.phone = phone

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 435)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.sfdg = QtWidgets.QWidget()
        self.sfdg.setObjectName("sfdg")
        self.label_6 = QtWidgets.QLabel(self.sfdg)
        self.label_6.setGeometry(QtCore.QRect(150, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(self.sfdg)
        self.label_12.setGeometry(QtCore.QRect(414, 60, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.fname = QtWidgets.QLineEdit(self.sfdg)
        self.fname.setGeometry(QtCore.QRect(392, 80, 161, 20))
        self.fname.setObjectName("fname")
        self.label_15 = QtWidgets.QLabel(self.sfdg)
        self.label_15.setGeometry(QtCore.QRect(230, 60, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lname = QtWidgets.QLineEdit(self.sfdg)
        self.lname.setGeometry(QtCore.QRect(200, 80, 161, 20))
        self.lname.setObjectName("lname")
        self.label_16 = QtWidgets.QLabel(self.sfdg)
        self.label_16.setGeometry(QtCore.QRect(400, 120, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.combo_insurance_panel = QtWidgets.QComboBox(self.sfdg)
        self.combo_insurance_panel.setGeometry(QtCore.QRect(392, 150, 161, 22))
        self.combo_insurance_panel.setObjectName("combo_insurance_panel")
        self.label_17 = QtWidgets.QLabel(self.sfdg)
        self.label_17.setGeometry(QtCore.QRect(230, 120, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.image = QtWidgets.QLabel(self.sfdg)
        self.image.setGeometry(QtCore.QRect(20, 60, 151, 141))
        self.image.setObjectName("image")
        self.browseimage = QtWidgets.QPushButton(self.sfdg)
        self.browseimage.setGeometry(QtCore.QRect(200, 150, 91, 21))
        self.browseimage.setObjectName("browseimage")

        self.browseimage.clicked.connect(self.Browse_Image)
        self.update_panel = QtWidgets.QPushButton(self.sfdg)
        self.update_panel.setGeometry(QtCore.QRect(195, 320, 361, 31))
        self.update_panel.setObjectName("update_panel")

        self.update_panel.clicked.connect(self.Update_Panel)
        self.label_19 = QtWidgets.QLabel(self.sfdg)
        self.label_19.setGeometry(QtCore.QRect(420, 180, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.dateEdit = QtWidgets.QDateEdit(self.sfdg)
        self.dateEdit.setGeometry(QtCore.QRect(389, 210, 161, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_20 = QtWidgets.QLabel(self.sfdg)
        self.label_20.setGeometry(QtCore.QRect(230, 180, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.female = QtWidgets.QRadioButton(self.sfdg)
        self.female.setGeometry(QtCore.QRect(201, 210, 61, 20))
        self.female.setObjectName("female")
        self.male = QtWidgets.QRadioButton(self.sfdg)
        self.male.setGeometry(QtCore.QRect(291, 210, 61, 20))
        self.male.setObjectName("male")
        self.label_21 = QtWidgets.QLabel(self.sfdg)
        self.label_21.setGeometry(QtCore.QRect(250, 250, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.password = QtWidgets.QLineEdit(self.sfdg)
        self.password.setGeometry(QtCore.QRect(390, 280, 161, 20))
        self.password.setObjectName("password")
        self.tabWidget.addTab(self.sfdg, "")
        self.asdfg = QtWidgets.QWidget()
        self.asdfg.setObjectName("asdfg")
        self.label_8 = QtWidgets.QLabel(self.asdfg)
        self.label_8.setGeometry(QtCore.QRect(144, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_18 = QtWidgets.QLabel(self.asdfg)
        self.label_18.setGeometry(QtCore.QRect(470, 50, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.chose_family = QtWidgets.QComboBox(self.asdfg)
        self.chose_family.setGeometry(QtCore.QRect(410, 70, 161, 22))
        self.chose_family.setObjectName("chose_family")
        self.list_appointment = QtWidgets.QListView(self.asdfg)
        self.list_appointment.setGeometry(QtCore.QRect(10, 51, 201, 311))
        self.list_appointment.setObjectName("list_appointment")

        list_appointment_model = QtGui.QStandardItemModel()
        self.list_appointment.setModel(list_appointment_model)

        return_list_appointment = self.db_fetch_appointment()

        for i in return_list_appointment:                
            item = QtGui.QStandardItem(str(i))
            item.setEditable(False)
            list_appointment_model.appendRow(item)

        self.list_appointment.clicked.connect(self.set_label_appointment)
        self.list_appointment.setStyleSheet("QListView::item:!selected { border-bottom: 1px solid black; padding: 2px; }")
        
        self.label_22 = QtWidgets.QLabel(self.asdfg)
        self.label_22.setGeometry(QtCore.QRect(244, 50, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.appointment_label = QtWidgets.QLabel(self.asdfg)
        self.appointment_label.setGeometry(QtCore.QRect(230, 79, 161, 231))
        self.appointment_label.setObjectName("appointment_label")
        self.label_24 = QtWidgets.QLabel(self.asdfg)
        self.label_24.setGeometry(QtCore.QRect(410, 100, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.combo_specialty_appointment = QtWidgets.QComboBox(self.asdfg)
        self.combo_specialty_appointment.setGeometry(QtCore.QRect(408, 189, 161, 20))
        self.combo_specialty_appointment.setObjectName("combo_specialty_appointment")
        self.label_25 = QtWidgets.QLabel(self.asdfg)
        self.label_25.setGeometry(QtCore.QRect(408, 171, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.search_doctor_appointment = QtWidgets.QLineEdit(self.asdfg)
        self.search_doctor_appointment.setGeometry(QtCore.QRect(408, 148, 161, 20))
        self.search_doctor_appointment.setObjectName("search_doctor_appointment")
        self.label_26 = QtWidgets.QLabel(self.asdfg)
        self.label_26.setGeometry(QtCore.QRect(428, 130, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.asdfg)
        self.label_27.setGeometry(QtCore.QRect(408, 212, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.find_appointment = QtWidgets.QPushButton(self.asdfg)
        self.find_appointment.setGeometry(QtCore.QRect(450, 320, 71, 21))
        self.find_appointment.setObjectName("find_appointment")

        self.find_appointment.clicked.connect(self.Find_Appointment)
        self.dateEdit_appointment = QtWidgets.QDateEdit(self.asdfg)
        self.dateEdit_appointment.setGeometry(QtCore.QRect(409, 230, 161, 22))
        self.dateEdit_appointment.setObjectName("dateEdit_appointment")
        self.label_28 = QtWidgets.QLabel(self.asdfg)
        self.label_28.setGeometry(QtCore.QRect(410, 260, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.timeEdit_appointment = QtWidgets.QTimeEdit(self.asdfg)
        self.timeEdit_appointment.setGeometry(QtCore.QRect(410, 280, 161, 22))
        self.timeEdit_appointment.setObjectName("timeEdit_appointment")
        self.profile_doctor_appointment = QtWidgets.QPushButton(self.asdfg)
        self.profile_doctor_appointment.setGeometry(QtCore.QRect(225, 330, 181, 20))
        self.profile_doctor_appointment.setObjectName("profile_doctor_appointment")

        self.profile_doctor_appointment.clicked.connect(self.Profile_Doctor_Appointment)
        self.score_doctor = QtWidgets.QSpinBox(self.asdfg)
        self.score_doctor.setGeometry(QtCore.QRect(280, 300, 42, 22))
        self.score_doctor.setMaximum(5)
        self.score_doctor.setObjectName("score_doctor")
        self.label_34 = QtWidgets.QLabel(self.asdfg)
        self.label_34.setGeometry(QtCore.QRect(330, 300, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.score_clicked = QtWidgets.QPushButton(self.asdfg)
        self.score_clicked.setGeometry(QtCore.QRect(220, 300, 56, 21))
        self.score_clicked.setObjectName("score_clicked")

        self.score_clicked.clicked.connect(self.Score_Clicked)
        self.tabWidget.addTab(self.asdfg, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(150, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.add_family = QtWidgets.QPushButton(self.tab_2)
        self.add_family.setGeometry(QtCore.QRect(335, 70, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_family.setFont(font)
        self.add_family.setObjectName("add_family")

        self.add_family.clicked.connect(self.Add_Family)
        self.list_family = QtWidgets.QListView(self.tab_2)
        self.list_family.setGeometry(QtCore.QRect(15, 51, 271, 301))
        self.list_family.setObjectName("list_family")

        list_family_model = QtGui.QStandardItemModel()
        self.list_family.setModel(list_family_model)

        return_list_family = self.db_fetch_family()

        for i in return_list_family:                
            item = QtGui.QStandardItem(str(i))
            item.setEditable(False)
            list_family_model.appendRow(item)

        self.list_family.clicked.connect(self.set_label_family)
        self.list_family.setStyleSheet("QListView::item:!selected { border-bottom: 1px solid black; padding: 2px; }")
        
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(360, 220, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.selected_family = QtWidgets.QLabel(self.tab_2)
        self.selected_family.setGeometry(QtCore.QRect(340, 250, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selected_family.setFont(font)
        self.selected_family.setText("")
        self.selected_family.setObjectName("selected_family")
        self.delete_selected_family = QtWidgets.QPushButton(self.tab_2)
        self.delete_selected_family.setGeometry(QtCore.QRect(420, 310, 141, 20))
        self.delete_selected_family.setObjectName("delete_selected_family")

        self.delete_selected_family.clicked.connect(self.Delete_Selected_Family)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(180, 10, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(271, 116, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.code_paygiry = QtWidgets.QLineEdit(self.tab_3)
        self.code_paygiry.setGeometry(QtCore.QRect(151, 148, 321, 20))
        self.code_paygiry.setObjectName("code_paygiry")
        self.paygiry = QtWidgets.QPushButton(self.tab_3)
        self.paygiry.setGeometry(QtCore.QRect(240, 210, 131, 21))
        self.paygiry.setObjectName("pushButton")

        self.paygiry.clicked.connect(self.Paygiry)
        self.tabWidget.addTab(self.tab_3, "")
        self.dfbg = QtWidgets.QWidget()
        self.dfbg.setObjectName("dfbg")
        self.list_doctor = QtWidgets.QListView(self.dfbg)
        self.list_doctor.setGeometry(QtCore.QRect(6, 56, 271, 301))
        self.list_doctor.setObjectName("list_doctor")

        list_doctor_model = QtGui.QStandardItemModel()
        self.list_doctor.setModel(list_doctor_model)

        return_list_doctor = self.db_fetch_doctor()

        for i in return_list_doctor:                
            item = QtGui.QStandardItem(str(i))
            item.setEditable(False)
            list_doctor_model.appendRow(item)

        self.list_doctor.clicked.connect(self.set_label_doctor)
        self.list_doctor.setStyleSheet("QListView::item:!selected { border-bottom: 1px solid black; padding: 2px; }")
        
        self.label = QtWidgets.QLabel(self.dfbg)
        self.label.setGeometry(QtCore.QRect(10, 0, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.find_doctor = QtWidgets.QPushButton(self.dfbg)
        self.find_doctor.setGeometry(QtCore.QRect(300, 120, 71, 41))
        self.find_doctor.setObjectName("find_doctor")

        self.find_doctor.clicked.connect(self.Find_Doctor)
        self.label_4 = QtWidgets.QLabel(self.dfbg)
        self.label_4.setGeometry(QtCore.QRect(320, 20, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.sort_vistprice = QtWidgets.QPushButton(self.dfbg)
        self.sort_vistprice.setGeometry(QtCore.QRect(310, 210, 241, 20))
        self.sort_vistprice.setObjectName("sort_vistprice")

        self.sort_vistprice.clicked.connect(self.Sort_Vistprice)
        self.widget = QtWidgets.QWidget(self.dfbg)
        self.widget.setGeometry(QtCore.QRect(380, 70, 181, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.search_name_doctor = QtWidgets.QLineEdit(self.widget)
        self.search_name_doctor.setObjectName("search_name_doctor")
        self.verticalLayout_6.addWidget(self.search_name_doctor)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.combo_specialty = QtWidgets.QComboBox(self.widget)
        self.combo_specialty.setObjectName("combo_specialty")
        self.verticalLayout_6.addWidget(self.combo_specialty)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.combo_insurance = QtWidgets.QComboBox(self.widget)
        self.combo_insurance.setObjectName("combo_insurance")
        self.verticalLayout_6.addWidget(self.combo_insurance)
        self.widget1 = QtWidgets.QWidget(self.dfbg)
        self.widget1.setGeometry(QtCore.QRect(300, 250, 261, 101))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.selected_doctor = QtWidgets.QLabel(self.widget1)
        self.selected_doctor.setText("")
        self.selected_doctor.setObjectName("selected_doctor")
        self.verticalLayout_7.addWidget(self.selected_doctor)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.appointment = QtWidgets.QPushButton(self.widget1)
        self.appointment.setObjectName("appointment")
        self.verticalLayout.addWidget(self.appointment)

        self.appointment.clicked.connect(self.Reserve_Appointment_Doctor_List)
        self.profile = QtWidgets.QPushButton(self.widget1)
        self.profile.setObjectName("profile")
        self.verticalLayout.addWidget(self.profile)
        self.verticalLayout_7.addLayout(self.verticalLayout)

        self.profile.clicked.connect(self.Profile_Doctor_List)
        self.tabWidget.addTab(self.dfbg, "")
        self.dfb = QtWidgets.QWidget()
        self.dfb.setObjectName("dfb")
        self.label_13 = QtWidgets.QLabel(self.dfb)
        self.label_13.setGeometry(QtCore.QRect(325, 20, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.dfb)
        self.label_14.setGeometry(QtCore.QRect(15, 0, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.list_healthcare = QtWidgets.QListView(self.dfb)
        self.list_healthcare.setGeometry(QtCore.QRect(11, 56, 271, 301))
        self.list_healthcare.setObjectName("list_healthcare")

        list_healthcare_model = QtGui.QStandardItemModel()
        self.list_healthcare.setModel(list_healthcare_model)

        return_list_healthcare = self.db_fetch_healthcare()

        for i in return_list_healthcare:                
            item = QtGui.QStandardItem(str(i))
            item.setEditable(False)
            list_healthcare_model.appendRow(item)

        self.list_healthcare.clicked.connect(self.set_label_healthcare)
        self.list_healthcare.setStyleSheet("QListView::item:!selected { border-bottom: 1px solid black; padding: 2px; }")
        
        self.find_healthcare = QtWidgets.QPushButton(self.dfb)
        self.find_healthcare.setGeometry(QtCore.QRect(305, 110, 71, 41))
        self.find_healthcare.setObjectName("find_healthcare")

        self.find_healthcare.clicked.connect(self.Find_Healthcare)
        self.widget2 = QtWidgets.QWidget(self.dfb)
        self.widget2.setGeometry(QtCore.QRect(390, 90, 171, 78))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.name_healthcare = QtWidgets.QLineEdit(self.widget2)
        self.name_healthcare.setObjectName("name_healthcare")
        self.verticalLayout_4.addWidget(self.name_healthcare)
        self.label_10 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.name_doctor = QtWidgets.QLineEdit(self.widget2)
        self.name_doctor.setObjectName("name_doctor")
        self.verticalLayout_4.addWidget(self.name_doctor)
        self.widget3 = QtWidgets.QWidget(self.dfb)
        self.widget3.setGeometry(QtCore.QRect(305, 220, 261, 111))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.select_healthcare = QtWidgets.QLabel(self.widget3)
        self.select_healthcare.setText("")
        self.select_healthcare.setObjectName("select_healthcare")
        self.verticalLayout_5.addWidget(self.select_healthcare)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.list_doctors_healthcare = QtWidgets.QPushButton(self.widget3)
        self.list_doctors_healthcare.setObjectName("list_doctors_healthcare")

        self.list_doctors_healthcare.clicked.connect(self.List_Doctors_Healthcare)
        self.verticalLayout_3.addWidget(self.list_doctors_healthcare)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.dfb, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(200, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.list_saved_doctor = QtWidgets.QListView(self.tab)
        self.list_saved_doctor.setGeometry(QtCore.QRect(10, 50, 271, 301))
        self.list_saved_doctor.setObjectName("list_saved_doctor")

        list_saved_model = QtGui.QStandardItemModel()
        self.list_saved_doctor.setModel(list_saved_model)

        return_list_saved = self.db_fetch_saved()

        for i in return_list_saved:                
            item = QtGui.QStandardItem(str(i))
            item.setEditable(False)
            list_saved_model.appendRow(item)

        self.list_saved_doctor.clicked.connect(self.set_label_saved)
        self.list_saved_doctor.setStyleSheet("QListView::item:!selected { border-bottom: 1px solid black; padding: 2px; }")
        
        self.selected_saved_doctor = QtWidgets.QLabel(self.tab)
        self.selected_saved_doctor.setGeometry(QtCore.QRect(310, 230, 259, 25))
        self.selected_saved_doctor.setText("")
        self.selected_saved_doctor.setObjectName("selected_saved_doctor")
        self.profile_saved_doctor = QtWidgets.QPushButton(self.tab)
        self.profile_saved_doctor.setGeometry(QtCore.QRect(310, 330, 257, 17))
        self.profile_saved_doctor.setObjectName("profile_saved_doctor")

        self.profile_saved_doctor.clicked.connect(self.Profile_Saved_Doctor)
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(310, 200, 259, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.reserve_saved_doctor = QtWidgets.QPushButton(self.tab)
        self.reserve_saved_doctor.setGeometry(QtCore.QRect(310, 310, 257, 17))
        self.reserve_saved_doctor.setObjectName("reserve_saved_doctor")

        self.reserve_saved_doctor.clicked.connect(self.Reserve_Saved_Doctor)
        self.delete_saved_doctor = QtWidgets.QPushButton(self.tab)
        self.delete_saved_doctor.setGeometry(QtCore.QRect(310, 270, 257, 17))
        self.delete_saved_doctor.setObjectName("delete_saved_doctor")

        self.delete_saved_doctor.clicked.connect(self.Delete_Saved_Doctor)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "مشخصات"))
        self.label_12.setText(_translate("MainWindow", "نام"))
        self.label_15.setText(_translate("MainWindow", "نام خانوادگی"))
        self.label_16.setText(_translate("MainWindow", "بیمه"))
        self.label_17.setText(_translate("MainWindow", "عکس"))
        self.image.setText(_translate("MainWindow", "عکس"))
        self.browseimage.setText(_translate("MainWindow", "بارگذاری عکس"))
        self.update_panel.setText(_translate("MainWindow", "ثبت تغییرات"))
        self.label_19.setText(_translate("MainWindow", "تاریخ تولد"))
        self.label_20.setText(_translate("MainWindow", "جنسیت"))
        self.female.setText(_translate("MainWindow", "زن"))
        self.male.setText(_translate("MainWindow", "مرد"))
        self.label_21.setText(_translate("MainWindow", "رمز عبور"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sfdg), _translate("MainWindow", "Tab 1"))
        self.label_8.setText(_translate("MainWindow", "نوبت های من و خانواده"))
        self.label_18.setText(_translate("MainWindow", "انتخاب اعضای خانواده"))
        self.label_22.setText(_translate("MainWindow", "مشخصات نوبت انتخاب شده:"))
        self.appointment_label.setText(_translate("MainWindow", "مشخصات"))
        self.label_24.setText(_translate("MainWindow", "جستجو"))
        self.label_25.setText(_translate("MainWindow", "تخصص"))
        self.label_26.setText(_translate("MainWindow", "نام پزشک"))
        self.label_27.setText(_translate("MainWindow", "تاریخ"))
        self.find_appointment.setText(_translate("MainWindow", "جستجو"))
        self.label_28.setText(_translate("MainWindow", "ساعت"))
        self.profile_doctor_appointment.setText(_translate("MainWindow", "مشاهده پروفایل پزشک نوبت انتخاب شده"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.asdfg), _translate("MainWindow", "Page"))
        self.label_29.setText(_translate("MainWindow", "خانواده"))
        self.add_family.setText(_translate("MainWindow", "افزودن عضو +"))
        self.label_30.setText(_translate("MainWindow", "عضو انتخاب شده:"))
        self.delete_selected_family.setText(_translate("MainWindow", "حذف عضو انتخاب شده"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Page"))
        self.label_32.setText(_translate("MainWindow", "پیگیری نوبت"))
        self.label_33.setText(_translate("MainWindow", "کد پیگیری"))
        self.pushButton.setText(_translate("MainWindow", "پیگیری"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.label.setText(_translate("MainWindow", "لیست پزشکان"))
        self.find_doctor.setText(_translate("MainWindow", "جستجو"))
        self.label_4.setText(_translate("MainWindow", "جستجو"))
        self.sort_vistprice.setText(_translate("MainWindow", "مرتب کردن بر اساس هزینه ویزیت"))
        self.label_2.setText(_translate("MainWindow", "نام پزشک"))
        self.label_3.setText(_translate("MainWindow", "تخصص"))
        self.label_5.setText(_translate("MainWindow", "بیمه"))
        self.label_7.setText(_translate("MainWindow", "پزشک انتخاب شده:"))
        self.appointment.setText(_translate("MainWindow", "رزرو نوبت"))
        self.profile.setText(_translate("MainWindow", "مشاهده پروفایل"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dfbg), _translate("MainWindow", "Tab 2"))
        self.label_13.setText(_translate("MainWindow", "جستجو"))
        self.label_14.setText(_translate("MainWindow", "لیست مراکز درمانی"))
        self.find_healthcare.setText(_translate("MainWindow", "جستجو"))
        self.label_11.setText(_translate("MainWindow", "نام مرکز درمانی"))
        self.label_10.setText(_translate("MainWindow", "نام پزشک"))
        self.label_9.setText(_translate("MainWindow", "مرکز درمانی انتخاب شده:"))
        self.list_doctors_healthcare.setText(_translate("MainWindow", "مشاهده لیست پزشکان"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dfb), _translate("MainWindow", "Page"))
        self.label_23.setText(_translate("MainWindow", "پزشکان ذخیره شده"))
        self.profile_3.setText(_translate("MainWindow", "مشاهده پروفایل"))
        self.label_31.setText(_translate("MainWindow", "پزشک انتخاب شده:"))
        self.appointment_3.setText(_translate("MainWindow", "رزرو نوبت"))
        self.appointment_4.setText(_translate("MainWindow", "حذف از لیست ذخیره شده ها"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
    
    def Browse_Image(self):
        pass
    def Update_Panel(self):
        pass
    def Find_Appointment(self):
        pass
    def Profile_Doctor_Appointment(self):
        pass
    def Add_Family(self):
        pass
    def Delete_Selected_Family(self):
        pass
    def Paygiry(self):
        pass
    def Find_Doctor(self):
        pass
    def Sort_Vistprice(self):
        pass
    def Reserve_Appointment_Doctor_List(self):
        pass
    def Profile_Doctor_List(self):
        profile_text = str(self.selected_doctor.text()).lower()
        if(len(profile_text) == 0 ):
            self.pop_message("پزشکی انتخاب نشده است")
        else:
            profile_list = profile_text.split("\n")
            # profile_list[0] = medical_code
            # go to profile doctor with this medical_code 
    def Find_Healthcare(self):
        pass
    def List_Doctors_Healthcare(self):
        pass
    def Profile_Saved_Doctor(self):
        pass
    def Reserve_Saved_Doctor(self):
        pass
    def Delete_Saved_Doctor(self):
        pass
    def Score_Clicked(self):
        pass
   
    def set_label_doctor(self,index):
        # row = index.row()
        self.selected_doctor.setText(str(self.list_doctor.model().itemData(index)[0]))
    def set_label_appointment(self,index):
        self.appointment_label.setText(str(self.list_appointment.model().itemData(index)[0]))
    def set_label_family(self,index):
        self.selected_family.setText(str(self.list_family.model().itemData(index)[0]))        
    def set_label_healthcare(self,index):
        self.select_healthcare.setText(str(self.list_healthcare.model().itemData(index)[0]))        
    def set_label_saved(self,index):
        self.selected_saved_doctor.setText(str(self.list_saved_doctor.model().itemData(index)[0]))        

    def find_clicked(self):# pushbuttom
        filter_text = str(self.search.text()).lower()
        for row in range(self.listView_2.model().rowCount()):
            if filter_text in str(self.listView_2.model().item(row).text()).lower():
                self.listView_2.setRowHidden(row, False)
            else:
                self.listView_2.setRowHidden(row, True)

    # def searchItem(self, model):
    #     search_string = self.search.text() # Created a QlineEdit to input search strings
    #     items = self.listView_2.model().findItems(search_string, QtCore.Qt.MatchStartsWith)
    #     print(search_string)
    #     print(items)
    #     if len(items) > 0:
    #         for item in items:
    #             if search_string:
    #                 self.model.takeRow(item.row()) #take row of item
    #                 self.model.insertRow(0, item)  # and bring it to the top
    #     else:
    #         print ("not found")
    def pop_message(self,text):
        msg=QtWidgets.QMessageBox()
        msg.setText("{}".format(text))
        msg.setWindowTitle("خطا")
        msg.exec_()           

    def db_fetch_appointment(self):
        pass
    def db_fetch_family(self):
        pass
    def db_fetch_healthcare(self):
        pass
    def db_fetch_saved(self):
        pass
    def db_fetch_doctor(self):
        conn = sqlite3.connect('tabib.db')
        cursor = conn.cursor()

        cursor.execute("SELECT * FROM DOCTOR")
        val = cursor.fetchall()
        newlist =[]
        for i in val:
            newlist.append(f"{i[0]}\n{i[2]}\n{i[3]}\n{i[4]}\n{i[7]}") #medi,fname,lname,photo,specialty        
        conn.commit()
        cursor.close()
        conn.close()
        return newlist

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
